language: python
python:
  - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gfortran libgomp1 liblapack-pic

install: "pip install -r requirements.txt ."

script: nosetests
